### ISSUE TITLE
COMFAST CF-926AC

### ISSUE THREAD

**Issue by kabraloka** [ulli-kroll/mt7612u#27]
Hello,

According to https://www.cnx-software.com/2017/08/11/a-look-at-some-usb-3-0-wifi-802-11ac-adapters-with-multiple-high-gain-antennas/ I could use this driver for my COMFAST CF-926AC in my Linux box.

uname -a:

Linux X 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

lsusb gives me this info for the COMFAST CF-926AC:

...
Bus 002 Device 011: ID 0e8d:2870 MediaTek Inc. 
...

As I see that at common/rtusb_dev_id.c this usb id is not informed, then I include it like this:

...
{ USB_DEVICE(0x0e8d, 0x2870) }, /* COMFAST CF-926AC */
{ USB_DEVICE(0x057c, 0x8503) },	/*  AVM FRITZ!WLAN USB Stick AC 860 */
...

Then I compiled and installed the driver:

make
sudo make installfw
sudo cp mt7612u.ko /lib/modules/4.10.0-35-generic/kernel/drivers/
sudo depmod

And I reboot the Computer. After boot I can see at dmesg:

[   16.907823] mt7612u: loading out-of-tree module taints kernel.
[   16.908220] mt7612u: module verification failed: signature and/or required key missing - tainting kernel
[   16.910865] rtusb init mt7612u --->
[   16.910898] usbcore: registered new interface driver mt7612u

At lsmod | grep mt7612u I can see:

mt7612u               737280  0
cfg80211              602112  1 mt7612u

And iwconfig gives me:

enp2s0    no wireless extensions.
lo        no wireless extensions.

so, device doesn't seem to be installed.

I unattach my COMFAST CF-926AC and reattach it. Here is the log at dmesg for that action:

[ 2555.102040] usb 2-2: new high-speed USB device number 11 using xhci_hcd
[ 2555.243077] usb 2-2: New USB device found, idVendor=0e8d, idProduct=2870
[ 2555.243080] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2555.243081] usb 2-2: Product: Љ
[ 2555.243083] usb 2-2: Manufacturer: Љ
[ 2555.243084] usb 2-2: SerialNumber: Љ
[ 2555.243722] usb-storage 2-2:1.0: USB Mass Storage device detected
[ 2555.244088] scsi host4: usb-storage 2-2:1.0
[ 2556.258885] scsi 4:0:0:0: CD-ROM            MediaTek Flash autorun    0.01 PQ: 0 ANSI: 0 CCS
[ 2556.260312] sr 4:0:0:0: [sr1] scsi3-mmc drive: 52x/52x cd/rw xa/form2 cdda tray
[ 2556.260588] sr 4:0:0:0: Attached scsi CD-ROM sr1
[ 2556.260725] sr 4:0:0:0: Attached scsi generic sg2 type 5

The storage registered is embedded in the COMFAST CF-926AC as installation disk for windows.

And again I can not see the wireless at iwconfig nor any variation at lsmod | grep mt7612u.

What I am missing?

Thank you

**Comment by kabraloka** [comment]
I switched the mass storage for the wifi device with the command:

`sudo usb_modeswitch -KW -v 0e8d -p 2870`

And I then I got for lsusb:

`Bus 002 Device 007: ID 0e8d:7612 MediaTek Inc. `

and for lsusb -t:

`    |__ Port 2: Dev 7, If 0, Class=Vendor Specific Class, Driver=mt7612u, 480M`

At dmesg I got  the driver load log:

`[  156.246967] usb 2-2: USB disconnect, device number 3`
`[  157.169740] usb 2-2: new high-speed USB device number 7 using xhci_hcd`
`[  157.311091] usb 2-2: New USB device found, idVendor=0e8d, idProduct=7612`
`[  157.311093] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3`
`[  157.311094] usb 2-2: Product: 802.11ac WLAN`
`[  157.311094] usb 2-2: Manufacturer: MediaTek Inc.`
`[  157.311095] usb 2-2: SerialNumber: 000000000`
`[  157.312014] `
`               `
`               === pAd = ffffa9f6023f4000, size = 1275904 ===`
`               `
`[  157.312080] <-- RTMPAllocTxRxRingMemory, Status=0`
`[  157.312095] <-- RTMPAllocAdapterBlock, Status=0`
`[  157.312305] ==>mt7612u_chip_onoff(): OnOff:1, Reset= 1, pAd->WlanFunCtrl:0x0, Reg-WlanFunCtrl=0x20a`
`[  157.330606] Endpoint(8) is for In-band Command`
`[  157.330607] Endpoint(4) is for WMM0 AC0`
`[  157.330607] Endpoint(5) is for WMM0 AC1`
`[  157.330608] Endpoint(6) is for WMM0 AC2`
`[  157.330608] Endpoint(7) is for WMM0 AC3`
`[  157.330609] Endpoint(9) do not pair`
`[  157.330609] Invalid bulk out ep(9)`
`[  157.330610] Endpoint(84) is for Data-In`
`[  157.330610] Endpoint(85) is for Command Rsp`
`[  157.330733] 80211> RFICType= 3, NumOfChan= 58`
`[  157.330734] 80211> Number of rate = 12`
`[  157.330735] 80211> CurTxPower = 20 dBm`
`[  157.330735] ====> Rader Channel 52`
`[  157.330736] ====> Rader Channel 54`
`[  157.330736] ====> Rader Channel 56`
`[  157.330736] ====> Rader Channel 60`
`[  157.330737] ====> Rader Channel 62`
`[  157.330737] ====> Rader Channel 64`
`[  157.330737] ====> Rader Channel 100`
`[  157.330738] ====> Rader Channel 104`
`[  157.330738] 80211> TxStream = 0`
`[  157.330896] 80211> CFG80211_Register`
`[  157.871851] show_signal_msg: 11 callbacks suppressed`
`[  157.871855] ModemManager[1000]: segfault at 0 ip 00005635554f8ab7 sp 00007ffee84ed990 error 4 in ModemManager[5635554c1000+11f000]`

I see at iwconfig:

`lo        no wireless extensions.`
`enp2s0    no wireless extensions.`
`wlan0     Ralink STA`

so I type ifconfig wlan0 up 
and I get at ifconfig:

`wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500`
`        ether 40:ff:ff:ff:ff:ff  txqueuelen 1000  (Ethernet)`
`        RX packets 0  bytes 0 (0.0 B)`
`        RX errors 0  dropped 0  overruns 0  frame 0`
`        TX packets 0  bytes 0 (0.0 B)`
`        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

At dmesg, for ifconfig wlan0 up  command I get:

`[  232.488241] usb 2-2: loading firmware patch mt7662u_rom_patch.bin`
`[  232.521844] usb 2-2: firmware mt7662u.bin patch loaded`
`[  232.537252] build time = `
`[  232.537253] 2`
`[  232.537253] 0`
`[  232.537253] 1`
`[  232.537254] 4`
`[  232.537254] 0`
`[  232.537254] 4`
`[  232.537254] 0`
`[  232.537255] 8`
`[  232.537255] 0`
`[  232.537255] 6`
`[  232.537255] 0`
`[  232.537256] 6`
`[  232.537256] 4`
`[  232.537256] 0`
`[  232.537256] a`
`                `
`[  232.537257] rom patch for E3 IC`
`                `
`[  232.537258] platform =`
`[  232.537258] A`
`[  232.537258] L`
`[  232.537258] P`
`[  232.537259] S`
`                `
`[  232.537259] hw/sw version =`
`[  232.537260] \xffffff8a`
`[  232.537260] `
`[  232.537260] \xffffff8a`
`[  232.537260] `
`                `
`[  232.537261] patch version =`
`[  232.537261] `
`[  232.537261] `
`[  232.537262] `
`[  232.537262] `
`                `
`[  232.548111] loading rom patch`
`[  232.548112] pos = 0`
`[  232.548113] sent_len = 2040`
`[  232.548447] .`
`[  232.553601] pos = 2040`
`[  232.553601] sent_len = 2040`
`[  232.564253] .`
`[  232.569414] pos = 4080`
`[  232.569414] sent_len = 2040`
`[  232.580070] .`
`[  232.585404] pos = 6120`
`[  232.585405] sent_len = 2040`
`[  232.595762] .`
`[  232.600910] pos = 8160`
`[  232.600910] sent_len = 2040`
`[  232.611262] .`
`[  232.616411] pos = 10200`
`[  232.616411] sent_len = 2040`
`[  232.626922] .`
`[  232.632240] pos = 12240`
`[  232.632241] sent_len = 2040`
`[  232.642758] .`
`[  232.647983] pos = 14280`
`[  232.647984] sent_len = 2040`
`[  232.658635] .`
`[  232.663912] pos = 16320`
`[  232.663914] sent_len = 2040`
`[  232.674444] .`
`[  232.679736] pos = 18360`
`[  232.679737] sent_len = 2040`
`[  232.690146] .`
`[  232.695302] pos = 20400`
`[  232.695303] sent_len = 256`
`[  232.705827] .`
`[  232.716060] Send checksum req..`
`[  232.716062] mt7612u_mcu_usb_chk_crc`
`[  232.759759] mt7612u_mcu_usb_enable_patch`
`[  232.759971] mt7612u_mcu_usb_reset_wmt`
`[  232.790263] usb 2-2: loading firmware mt7662u.bin`
`[  232.798363] usb 2-2: firmware mt7662u.bin loaded`
`[  232.824046] fw version:0.0.00 `
`[  232.824047] build:1`
`[  232.824047] build time:`
`[  232.824048] 2`
`[  232.824058] 0`
`[  232.824058] 1`
`[  232.824058] 4`
`[  232.824058] 0`
`[  232.824059] 6`
`[  232.824059] 2`
`[  232.824059] 4`
`[  232.824059] 1`
`[  232.824060] 8`
`[  232.824060] 3`
`[  232.824060] 0`
`[  232.824060] _`
`[  232.824061] _`
`[  232.824061] _`
`[  232.824061] _`
`                `
`[  232.824062] fw for E3 IC`
`[  232.824063] ilm length = 59312(bytes)`
`[  232.824063] dlm length = 32068(bytes)`
`[  232.824780] loading fw`
`[  232.824781] pos = 0`
`[  232.824782] sent_len = 2040`
`[  232.825105] .`
`[  232.830261] pos = 2040`
`[  232.830261] sent_len = 2040`
`[  232.840885] .`
`[  232.846090] pos = 4080`
`[  232.846091] sent_len = 2040`
`[  232.856779] .`
`[  232.861983] pos = 6120`
`[  232.861984] sent_len = 2040`
`[  232.872708] .`
`[  232.877888] pos = 8160`
`[  232.877889] sent_len = 2040`
`[  232.888576] .`
`[  232.893762] pos = 10200`
`[  232.893763] sent_len = 2040`
`[  232.904421] .`
`[  232.909668] pos = 12240`
`[  232.909669] sent_len = 2040`
`[  232.920326] .`
`[  232.925582] pos = 14280`
`[  232.925582] sent_len = 2040`
`[  232.936196] .`
`[  232.941458] pos = 16320`
`[  232.941458] sent_len = 2040`
`[  232.952161] .`
`[  232.957418] pos = 18360`
`[  232.957419] sent_len = 2040`
`[  232.968077] .`
`[  232.973336] pos = 20400`
`[  232.973337] sent_len = 2040`
`[  232.983986] .`
`[  232.989276] pos = 22440`
`[  232.989277] sent_len = 2040`
`[  232.999959] .`
`[  233.005213] pos = 24480`
`[  233.005214] sent_len = 2040`
`[  233.015866] .`
`[  233.021084] pos = 26520`
`[  233.021086] sent_len = 2040`
`[  233.031512] .`
`[  233.036699] pos = 28560`
`[  233.036699] sent_len = 2040`
`[  233.047339] .`
`[  233.052617] pos = 30600`
`[  233.052619] sent_len = 2040`
`[  233.063354] .`
`[  233.068587] pos = 32640`
`[  233.068588] sent_len = 2040`
`[  233.079283] .`
`[  233.084651] pos = 34680`
`[  233.084652] sent_len = 2040`
`[  233.095496] .`
`[  233.100811] pos = 36720`
`[  233.100813] sent_len = 2040`
`[  233.111303] .`
`[  233.116534] pos = 38760`
`[  233.116535] sent_len = 2040`
`[  233.127516] .`
`[  233.132966] pos = 40800`
`[  233.132968] sent_len = 2040`
`[  233.143871] .`
`[  233.149070] pos = 42840`
`[  233.149072] sent_len = 2040`
`[  233.159878] .`
`[  233.165189] pos = 44880`
`[  233.165191] sent_len = 2040`
`[  233.176005] .`
`[  233.181323] pos = 46920`
`[  233.181324] sent_len = 2040`
`[  233.192052] .`
`[  233.197327] pos = 48960`
`[  233.197329] sent_len = 2040`
`[  233.207917] .`
`[  233.213207] pos = 51000`
`[  233.213208] sent_len = 2040`
`[  233.223984] .`
`[  233.229354] pos = 53040`
`[  233.229356] sent_len = 2040`
`[  233.240246] .`
`[  233.245538] pos = 55080`
`[  233.245539] sent_len = 2040`
`[  233.256307] .`
`[  233.261558] pos = 57120`
`[  233.261559] sent_len = 2040`
`[  233.272042] .`
`[  233.277311] pos = 59160`
`[  233.277313] sent_len = 152`
`[  233.288105] .`
`[  233.293357] pos = 0`
`[  233.293359] sent_len = 2040`
`[  233.304385] .`
`[  233.309718] pos = 2040`
`[  233.309719] sent_len = 2040`
`[  233.320099] .`
`[  233.325271] pos = 4080`
`[  233.325272] sent_len = 2040`
`[  233.336119] .`
`[  233.341389] pos = 6120`
`[  233.341391] sent_len = 2040`
`[  233.352259] .`
`[  233.357456] pos = 8160`
`[  233.357457] sent_len = 2040`
`[  233.368252] .`
`[  233.373527] pos = 10200`
`[  233.373528] sent_len = 2040`
`[  233.384266] .`
`[  233.389547] pos = 12240`
`[  233.389548] sent_len = 2040`
`[  233.400485] .`
`[  233.405744] pos = 14280`
`[  233.405746] sent_len = 2040`
`[  233.416258] .`
`[  233.421453] pos = 16320`
`[  233.421454] sent_len = 2040`
`[  233.432359] .`
`[  233.437715] pos = 18360`
`[  233.437717] sent_len = 2040`
`[  233.448185] .`
`[  233.453381] pos = 20400`
`[  233.453382] sent_len = 2040`
`[  233.464151] .`
`[  233.469424] pos = 22440`
`[  233.469426] sent_len = 2040`
`[  233.480258] .`
`[  233.485558] pos = 24480`
`[  233.485559] sent_len = 2040`
`[  233.496496] .`
`[  233.501748] pos = 26520`
`[  233.501750] sent_len = 2040`
`[  233.512265] .`
`[  233.517532] pos = 28560`
`[  233.517533] sent_len = 2040`
`[  233.528270] .`
`[  233.533520] pos = 30600`
`[  233.533521] sent_len = 1468`
`[  233.544343] .`
`                `
`[  233.581302] cfg_mode=13`
`[  233.581306] wmode_band_equal(): Band Not Equal!`
`[  233.581557] Key1Str is Invalid key length(0) or Type(0)`
`[  233.581575] Key2Str is Invalid key length(0) or Type(0)`
`[  233.581594] Key3Str is Invalid key length(0) or Type(0)`
`[  233.581612] Key4Str is Invalid key length(0) or Type(0)`
`[  233.582080] 1. Phy Mode = 61`
`[  233.592411] Use the MAC address what is assigned from EEPROM. `
`[  233.595087] PA Type 3`
`[  233.595204] EEPROM_NIC_CFG1_OFFSET = 0xff22`
`[  233.595333] Bluetooth Support word d7ff`
`[  233.595398] Country Region from e2p = ffff`
`[  233.596019] mt76x2_read_temp_info_from_eeprom:: is_temp_tx_alc=0, temp_tx_alc_enable=0`
`[  233.597459] mt76x2_get_external_lna_gain::LNA type=0x11, BLNAGain=0x0, ALNAGain0=0x0, ALNAGain1=0x0, ALNAGain2=0x0`
`[  233.597461] 2. Phy Mode = 61`
`[  233.597462] 3. Phy Mode = 61`
`[  233.597579] MAC[Ver=0x76623000]`
`[  233.597581] mt7612u_mcu_usb_fw_init`
`[  233.675296] mt7612u_mcu_load_cr:cr_type(2) temp_level(0) channel(0)`
`[  233.675798] InitFrequencyCalibration: frequency offset in the EEPROM = 148`
`[  233.675818] RTMPSetPhyMode: channel is out of range, use first channel=1 `
`[  233.675819] RTMPSetPhyMode: Update for STA`
`[  233.677510] MCS Set = ff ff 00 00 01`
`[  233.677525] <==== rt28xx_init, Status=0`
`[  233.677597] 80211> re-init bands...`
`[  233.677600] 80211> RFICType= 3, NumOfChan= 58`
`[  233.677601] 80211> Number of rate = 12`
`[  233.677602] 80211> CurTxPower = 20 dBm`
`[  233.677603] ====> Rader Channel 52`
`[  233.677604] ====> Rader Channel 54`
`[  233.677605] ====> Rader Channel 56`
`[  233.677606] ====> Rader Channel 60`
`[  233.677607] ====> Rader Channel 62`
`[  233.677608] ====> Rader Channel 64`
`[  233.677609] ====> Rader Channel 100`
`[  233.677610] ====> Rader Channel 104`
`[  233.677611] 80211> TxStream = 2`
`[  233.677620] Chan 167 (frq 5835):     not allowed!`
`[  233.677621] Chan 169 (frq 5845):     not allowed!`
`[  233.677622] Chan 171 (frq 5855):     not allowed!`
`[  233.677623] Chan 173 (frq 5865):     not allowed!`
`[  233.677624] Chan 184 (frq 4920):     not allowed!`
`[  233.677625] Chan 188 (frq 4940):     not allowed!`
`[  233.677626] Chan 192 (frq 4960):     not allowed!`
`[  233.677627] Chan 196 (frq 4980):     not allowed!`
`[  233.677628] Chan 208 (frq 6040):     not allowed!`
`[  233.677629] Chan 212 (frq 6060):     not allowed!`
`[  233.677630] Chan 216 (frq 6080):     not allowed!`
`[  233.677632] RTMPDrvOpen(1):Check if PDMA is idle!`
`[  233.677706] RTMPDrvOpen(2):Check if PDMA is idle!`

At Network Manager I see the WiFi activated. Still, no APs detected.

**Comment by kabraloka** [comment]
Little progress here. After calling ifconfig wlan0 up

iwlist wlan0 freq :
```
wlan0     47 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
          Channel 12 : 2.467 GHz
          Channel 13 : 2.472 GHz
          Channel 14 : 2.484 GHz
          Channel 36 : 5.18 GHz
          Channel 38 : 5.19 GHz
          Channel 40 : 5.2 GHz
          Channel 44 : 5.22 GHz
          Channel 46 : 5.23 GHz
          Channel 48 : 5.24 GHz
          Channel 52 : 5.26 GHz
          Channel 54 : 2.412 GHz
          Channel 56 : 5.28 GHz
          Channel 60 : 5.3 GHz
          Channel 62 : 2.412 GHz
          Channel 64 : 5.32 GHz
          Channel 100 : 5.5 GHz
          Channel 104 : 5.52 GHz
          Channel 108 : 5.54 GHz
          Channel 112 : 5.56 GHz
          Channel 116 : 5.58 GHz
          Channel 118 : 2.412 GHz
          Current Frequency=2.412 GHz (Channel 1)
```
iwlist wlan0 scan:
```
wlan0     Scan completed :
          Cell 01 - Address: 60:FF:FF:FF:FF:FE
                    Protocol:802.11b/g/n
                    ESSID:"WLAN1"
                    Mode:Managed
                    Frequency:2.462 GHz (Channel 11)
                    Quality=100/100  Signal level=-37 dBm  Noise level=-92 dBm
                    Encryption key:on
                    Bit Rates:54 Mb/s
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
          Cell 02 - Address: 60:FF:FF:FF:FF:FF
                    Protocol:802.11a/n
                    ESSID:"WLAN2"
                    Mode:Managed
                    Frequency:5.18 GHz (Channel 36)
                    Quality=100/100  Signal level=-36 dBm  Noise level=-92 dBm
                    Encryption key:on
                    Bit Rates:150 Mb/s
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
```

But nothing at Network Manager. At driver load syslog shows this:

```
Sep 23 14:14:05 X kernel: [  102.276177] usb 2-2: USB disconnect, device number 3
Sep 23 14:14:06 X kernel: [  103.199245] usb 2-2: new high-speed USB device number 7 using xhci_hcd
Sep 23 14:14:06 X kernel: [  103.340750] usb 2-2: New USB device found, idVendor=0e8d, idProduct=7612
Sep 23 14:14:06 X kernel: [  103.340754] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Sep 23 14:14:06 X kernel: [  103.340756] usb 2-2: Product: 802.11ac WLAN
Sep 23 14:14:06 X kernel: [  103.340758] usb 2-2: Manufacturer: MediaTek Inc.
Sep 23 14:14:06 X kernel: [  103.340760] usb 2-2: SerialNumber: 000000000
Sep 23 14:14:06 X kernel: [  103.342013] 
Sep 23 14:14:06 X kernel: [  103.342013] 
Sep 23 14:14:06 X kernel: [  103.342013] === pAd = ffffa060420ed000, size = 1275904 ===
Sep 23 14:14:06 X kernel: [  103.342013] 
Sep 23 14:14:06 X kernel: [  103.342151] <-- RTMPAllocTxRxRingMemory, Status=0
Sep 23 14:14:06 X kernel: [  103.342176] <-- RTMPAllocAdapterBlock, Status=0
Sep 23 14:14:06 X kernel: [  103.342401] ==>mt7612u_chip_onoff(): OnOff:1, Reset= 1, pAd->WlanFunCtrl:0x0, Reg-WlanFunCtrl=0x20a
Sep 23 14:14:06 X kernel: [  103.361729] Endpoint(8) is for In-band Command
Sep 23 14:14:06 X kernel: [  103.361731] Endpoint(4) is for WMM0 AC0
Sep 23 14:14:06 X kernel: [  103.361733] Endpoint(5) is for WMM0 AC1
Sep 23 14:14:06 X kernel: [  103.361734] Endpoint(6) is for WMM0 AC2
Sep 23 14:14:06 X kernel: [  103.361735] Endpoint(7) is for WMM0 AC3
Sep 23 14:14:06 X kernel: [  103.361736] Endpoint(9) do not pair
Sep 23 14:14:06 X kernel: [  103.361737] Invalid bulk out ep(9)
Sep 23 14:14:06 X kernel: [  103.361739] Endpoint(84) is for Data-In
Sep 23 14:14:06 X kernel: [  103.361740] Endpoint(85) is for Command Rsp
Sep 23 14:14:06 X kernel: [  103.361892] 80211> RFICType= 3, NumOfChan= 58
Sep 23 14:14:06 X kernel: [  103.361893] 80211> Number of rate = 12
Sep 23 14:14:06 X kernel: [  103.361895] 80211> CurTxPower = 20 dBm
Sep 23 14:14:06 X kernel: [  103.361897] ====> Rader Channel 52
Sep 23 14:14:06 X kernel: [  103.361898] ====> Rader Channel 54
Sep 23 14:14:06 X kernel: [  103.361899] ====> Rader Channel 56
Sep 23 14:14:06 X kernel: [  103.361900] ====> Rader Channel 60
Sep 23 14:14:06 X kernel: [  103.361901] ====> Rader Channel 62
Sep 23 14:14:06 X kernel: [  103.361902] ====> Rader Channel 64
Sep 23 14:14:06 X kernel: [  103.361903] ====> Rader Channel 100
Sep 23 14:14:06 X kernel: [  103.361904] ====> Rader Channel 104
Sep 23 14:14:06 X kernel: [  103.361906] 80211> TxStream = 0
Sep 23 14:14:06 X kernel: [  103.362232] 80211> CFG80211_Register
Sep 23 14:14:06 X NetworkManager[1011]: <info>  [1506165246.6620] (wlan0): using nl80211 for WiFi device control
Sep 23 14:14:06 X NetworkManager[1011]: <info>  [1506165246.6627] device (wlan0): driver supports Access Point (AP) mode
Sep 23 14:14:06 X NetworkManager[1011]: <info>  [1506165246.6661] manager: (wlan0): new 802.11 WiFi device (/org/freedesktop/NetworkManager/Devices/2)
Sep 23 14:14:06 X mtp-probe: checking bus 2, device 7: "/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2"
Sep 23 14:14:06 X mtp-probe: bus: 2, device: 7 was not an MTP device
Sep 23 14:14:06 X dbus[1006]: [system] Activating via systemd: service name='fi.w1.wpa_supplicant1' unit='wpa_supplicant.service'
Sep 23 14:14:06 X systemd[1]: Starting WPA supplicant...
Sep 23 14:14:06 X dbus[1006]: [system] Successfully activated service 'fi.w1.wpa_supplicant1'
Sep 23 14:14:06 X systemd[1]: Started WPA supplicant.
Sep 23 14:14:06 X wpa_supplicant[1668]: Successfully initialized wpa_supplicant
Sep 23 14:14:06 X NetworkManager[1011]: <info>  [1506165246.7239] supplicant: wpa_supplicant running
Sep 23 14:14:07 X NetworkManager[1011]: <info>  [1506165247.1915] rfkill1: found WiFi radio killswitch (at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/ieee80211/phy0/rfkill1) (driver usb)
Sep 23 14:14:07 X ifupdown-hotplug[1679]: Bad ifupdown udev helper invocation: $INTERFACE is not set
Sep 23 14:14:07 X systemd-udevd[1678]: Process 'ifupdown-hotplug' failed with exit code 1.
Sep 23 14:14:07 X kernel: [  103.937086] show_signal_msg: 11 callbacks suppressed
Sep 23 14:14:07 X kernel: [  103.937093] ModemManager[994]: segfault at 0 ip 0000562b7f352ab7 sp 00007ffe7bd3eab0 error 4 in ModemManager[562b7f31b000+11f000]
Sep 23 14:14:08 X systemd[1]: ModemManager.service: Main process exited, code=dumped, status=11/SEGV
Sep 23 14:14:08 X systemd[1]: ModemManager.service: Unit entered failed state.
Sep 23 14:14:08 X systemd[1]: ModemManager.service: Failed with result 'core-dump'.
Sep 23 14:14:08 X NetworkManager[1011]: <info>  [1506165248.3518] ModemManager disappeared from bus
Sep 23 14:14:08 X systemd[1]: ModemManager.service: Service hold-off time over, scheduling restart.
Sep 23 14:14:08 X systemd[1]: Stopped Modem Manager.
Sep 23 14:14:08 X systemd[1]: Starting Modem Manager...
Sep 23 14:14:08 X ModemManager[1686]: <info>  ModemManager (version 1.6.4) starting in system bus...
Sep 23 14:14:08 X NetworkManager[1011]: <info>  [1506165248.6301] ModemManager disappeared from bus
Sep 23 14:14:08 X systemd[1]: Started Modem Manager.
Sep 23 14:14:08 X NetworkManager[1011]: <info>  [1506165248.6415] ModemManager available in the bus
Sep 23 14:14:11 X ModemManager[1686]: <info>  Couldn't check support for device at '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2': not supported by any plugin
Sep 23 14:14:11 X ModemManager[1686]: <info>  Couldn't check support for device at '/sys/devices/pci0000:00/0000:00:1c.2/0000:02:00.0': not supported by any plugin
```

So, I try to reload network Manager ( service network-manager restart ) after ifconfig wlan0 up and I get this at syslog:

```
Sep 23 14:17:07 X systemd[1]: Stopped Network Manager Wait Online.
Sep 23 14:17:07 X systemd[1]: Stopping Network Manager Wait Online...
Sep 23 14:17:07 X systemd[1]: Stopping Network Manager...
Sep 23 14:17:07 X NetworkManager[1011]: <info>  [1506165427.8624] caught SIGTERM, shutting down normally.
Sep 23 14:17:07 X NetworkManager[1011]: <info>  [1506165427.9776] exiting (success)
Sep 23 14:17:07 X systemd[1]: Stopped Network Manager.
Sep 23 14:17:08 X systemd[1]: Starting Network Manager...
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0155] NetworkManager (version 1.4.4) is starting...
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0156] Read config: /etc/NetworkManager/NetworkManager.conf (lib: 10-dns-resolved.conf) (run: 10-globally-managed-devices.conf) (etc: default-wifi-powersave-on.conf)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0189] manager[0x555d74153040]: monitoring kernel firmware directory '/lib/firmware'.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0189] monitoring ifupdown state file '/run/network/ifstate'.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0202] dns-mgr[0x555d7414d950]: init: dns=systemd-resolved, rc-manager=symlink, plugin=systemd-resolved
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0211] rfkill1: found WiFi radio killswitch (at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/ieee80211/phy0/rfkill1) (driver usb)
Sep 23 14:17:08 X systemd[1]: Started Network Manager.
Sep 23 14:17:08 X dbus[1006]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Sep 23 14:17:08 X systemd[1]: Starting Network Manager Wait Online...
Sep 23 14:17:08 X systemd[1]: Starting Network Manager Script Dispatcher Service...
Sep 23 14:17:08 X dbus[1006]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Sep 23 14:17:08 X systemd[1]: Started Network Manager Script Dispatcher Service.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0350] init!
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0353] management mode: unmanaged
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0356] devices added (path: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/net/wlan0, iface: wlan0)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0356] device added (path: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/net/wlan0, iface: wlan0): no ifupdown configuration found.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0356] devices added (path: /sys/devices/pci0000:00/0000:00:1c.2/0000:02:00.0/net/enp2s0, iface: enp2s0)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0356] device added (path: /sys/devices/pci0000:00/0000:00:1c.2/0000:02:00.0/net/enp2s0, iface: enp2s0): no ifupdown configuration found.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0356] devices added (path: /sys/devices/virtual/net/lo, iface: lo)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0357] device added (path: /sys/devices/virtual/net/lo, iface: lo): no ifupdown configuration found.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0357] end _init.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0357] settings: loaded plugin ifupdown: (C) 2008 Canonical Ltd.  To report bugs please use the NetworkManager mailing list. (/usr/lib/x86_64-linux-gnu/NetworkManager/libnm-settings-plugin-ifupdown.so)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0357] settings: loaded plugin keyfile: (c) 2007 - 2015 Red Hat, Inc.  To report bugs please use the NetworkManager mailing list.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0357] (1947651120) ... get_connections.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0357] (1947651120) ... get_connections (managed=false): return empty list.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0463] keyfile: new connection /etc/NetworkManager/system-connections/>>0_0<< (1be00d5b-18ac-4443-9059-b7491d945f0e,">>0_0<<")
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0563] keyfile: new connection /etc/NetworkManager/system-connections/o_0 (424cab57-8289-43bd-96a2-9d5c656771a8,"o_0")
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0658] keyfile: new connection /etc/NetworkManager/system-connections/-O_O- (6eb30eef-6b78-4df2-a3c0-399fb888ef23,"-O_O-")
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.0665] get unmanaged devices count: 0
Sep 23 14:17:08 X dbus[1006]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
Sep 23 14:17:08 X systemd[1]: Starting Hostname Service...
Sep 23 14:17:08 X dbus[1006]: [system] Successfully activated service 'org.freedesktop.hostname1'
Sep 23 14:17:08 X systemd[1]: Started Hostname Service.
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2045] settings: hostname: using hostnamed
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2045] settings: hostname changed from (none) to "X"
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2047] dhcp-init: Using DHCP client 'dhclient'
Sep 23 14:17:08 X nm-dispatcher: req:1 'hostname': new request (2 scripts)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2047] manager: WiFi enabled by radio killswitch; enabled by state file
Sep 23 14:17:08 X nm-dispatcher: req:1 'hostname': start running ordered scripts...
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2047] manager: WWAN enabled by radio killswitch; enabled by state file
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2048] manager: Networking is enabled by state file
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2048] Loaded device plugin: NMVxlanFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2048] Loaded device plugin: NMVlanFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2049] Loaded device plugin: NMVethFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2049] Loaded device plugin: NMTunFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2049] Loaded device plugin: NMMacvlanFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2049] Loaded device plugin: NMIPTunnelFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2050] Loaded device plugin: NMInfinibandFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2050] Loaded device plugin: NMEthernetFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2050] Loaded device plugin: NMBridgeFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2051] Loaded device plugin: NMBondFactory (internal)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2073] Loaded device plugin: NMBluezManager (/usr/lib/x86_64-linux-gnu/NetworkManager/libnm-device-plugin-bluetooth.so)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2077] Loaded device plugin: NMAtmManager (/usr/lib/x86_64-linux-gnu/NetworkManager/libnm-device-plugin-adsl.so)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2080] Loaded device plugin: NMWwanFactory (/usr/lib/x86_64-linux-gnu/NetworkManager/libnm-device-plugin-wwan.so)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2084] Loaded device plugin: NMWifiFactory (/usr/lib/x86_64-linux-gnu/NetworkManager/libnm-device-plugin-wifi.so)
Sep 23 14:17:08 X NetworkManager[1817]: ((devices/nm-device.c:970)): assertion '<dropped>' failed
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2094] device (lo): link connected
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2104] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/0)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2118] manager: (enp2s0): new Ethernet device (/org/freedesktop/NetworkManager/Devices/1)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2127] keyfile: add connection in-memory (13c4b08e-6034-3b89-a802-595b5d88f990,"Wired connection 1")
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2132] settings: (enp2s0): created default wired connection 'Wired connection 1'
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2143] device (enp2s0): state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2152] (wlan0): using nl80211 for WiFi device control
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2154] device (wlan0): driver supports Access Point (AP) mode
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2162] manager: (wlan0): new 802.11 WiFi device (/org/freedesktop/NetworkManager/Devices/2)
Sep 23 14:17:08 X NetworkManager[1817]: <info>  [1506165428.2173] device (wlan0): state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
Sep 23 14:17:08 X kernel: [  284.908858] IPv6: ADDRCONF(NETDEV_UP): enp2s0: link is not ready
Sep 23 14:17:08 X kernel: [  284.953775] ==>mt7612u_chip_onoff(): OnOff:0, Reset= 0, pAd->WlanFunCtrl:0x20b, Reg-WlanFunCtrl=0x20b
```

At this point the system becomes unstable (frozen) and I can not do other thing than hard power off the PC, maybe mt7612u_chip_onoff() call has something to do with the freeze.

**Comment by ikin77** [comment]
Hi. Thanks for the info you've provided. Where you able to make it work. I've Ubuntu 16.04 and I've the same problems you're describing. Did you try also this driver?

https://github.com/jurobystricky/Netgear-A6210

I tried it. Before compiling, I added the line "{USB_DEVICE(0x0E8D, 0x2870), .driver_info = RLT_MAC_BASE}," in rtusb_dev_id.c.

It happend to me that JUST ONCE, after reboot, I saw the confast working flawlessly in NetworkManager. Then, after another reboot it disappeared.

Thanks in advance and best regards.

**Comment by ikin77** [comment]
SOLVED!!!!!!

1 - Remove this driver
2 - Install https://github.com/jurobystricky/Netgear-A6210. Follow the provided compiling instructions in my previous post.
3 - Avoid old ralink driver:

# cd /etc/modprobe.d
echo "blacklist rt2800lib" > rt2800lib.conf
echo "blacklist rt2800pci" > rt2800pci.conf
echo "blacklist rt2800usb" > rt2800usb.conf
echo "blacklist rt2x00lib" > rt2x00lib.conf
echo "blacklist rt2x00pci" > rt2x00pci.conf
echo "blacklist rt2x00usb" > rt2x00usb.conf
echo "blacklist rt61pci" > rt61pci.conf

Done!!!

**Comment by kabraloka** [comment]
I uninstalled previuos drivers and installed the driver @ jurobystricky/Netgear-A6210 following your instructions.

Comfast CF-926AC is recognized by the system and by enabled in the network-manager. Curiously it doesn't switch on the blue light but still shows the wifi networks in range in the network-manager. Anyway, it doesn't connect to any wifi network after several tries and getting sure that credentials/configs are correct. I haven't investigate any further in the logs. I just gave up with Comfast CF-926AC... I got a cheap **Comfast CF912AC 1200Mbps (with RTL8812AU chipset)** and it is **working very nicely in Linux** following this instructions:
https://blog.danielscrivano.com/installing-rtl8812au-on-linux-for-wireless-dual-band-usb-adapters/
To those who are loosing their minds with mt7612u and just want a cheap 1200Mbps wifi usb3.0 network receiver, I can tell that Comfast CF912AC is working fine in Linux with kernel 4.10.0.

Coming back to Comfast CF-926AC, If you are interested in any log for the wifi connection failures just ask, I will find some time to reply if someone is listening... BTW, was your Comfast CF-926AC blue light switched on when plugged?

Thanks for your help :-)

**Comment by ikin77** [comment]
Hi. Thanks to you for your previous research, with helped me to solve eventually the solution. I'm running Ubuntu 16.4, with no issues related with authentication phase. Actually, my Comfast CF-926AC is running flawlessly (2.4GHz & 5GHz) since I followed the steps described above.

Best regards

**Comment by gros319** [comment]
I i'm using the new parrot security 4.0 and I cannot install my confast cs-926AC V2 any ideas?

**Comment by artificerpi** [comment]
Just update the solution, Linux Kernel 5.0 is released today, and it includes the mt76x2 driver [committed by LorenzoBianconi](https://github.com/torvalds/linux/commit/cac97ed681db9891c74be91b54e6b550dc6afb03). After installing the [5.0 kernel in ubuntu](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.0/), everything works fine.

```
[  594.661721] usb 1-2: USB disconnect, device number 2
[  595.592764] usb 1-2: new high-speed USB device number 8 using xhci_hcd
[  595.742876] usb 1-2: New USB device found, idVendor=0e8d, idProduct=7612, bcdDevice= 1.00
[  595.742882] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  595.742886] usb 1-2: Product: 802.11ac WLAN
[  595.742890] usb 1-2: Manufacturer: MediaTek Inc.
[  595.742894] usb 1-2: SerialNumber: 000000000
[  595.983121] EXT4-fs (sdb1): re-mounted. Opts: errors=remount-ro,commit=360
[  597.685411] usb 1-2: reset high-speed USB device number 8 using xhci_hcd
[  597.840883] mt76x2u 1-2:1.0: ASIC revision: 76120044
[  597.877028] mt76x2u 1-2:1.0: ROM patch build: 20141115060606a
[  598.026922] mt76x2u 1-2:1.0: Firmware Version: 0.0.00
[  598.026923] mt76x2u 1-2:1.0: Build: 1
[  598.026924] mt76x2u 1-2:1.0: Build Time: 201507311614____
[  598.841870] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[  598.843478] usbcore: registered new interface driver mt76x2u
[  598.932784] EXT4-fs (sdb1): re-mounted. Opts: errors=remount-ro,commit=360
[  600.518444] mt76x2u 1-2:1.0 wlx40a5eff2b655: renamed from wlan0
```

Note that you should still switch mass storage into wifi device:
```bash
sudo usb_modeswitch -KW -v 0e8d -p 2870
```
